'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const fsp=fs.promises;const os=require('os');const path=require('path');const {normalize,correlate,listZip,sha,analyzeFiles}=require('../src/analyzer');const {removeXmlFields}=require('../src/cleaner');
test('normalizes evidence values',()=>assert.equal(normalize(' C:\\Users\\Alice  '),'c:/users/alice'));
test('correlation requires different suppliers and explains evidence',()=>{const base={zipName:'x.zip',files:[{zipPath:'a.docx',sha256:'x',attributes:{lastEditor:'rare-user'}}]};const f=correlate([{...base,supplier:'甲'},{...base,supplier:'乙'}]);assert.ok(f.some(x=>x.type==='相同文件'));assert.ok(f.every(x=>x.reason&&x.files.length===2));});
test('zip path traversal is rejected',async()=>{const dir=await fsp.mkdtemp(path.join(os.tmpdir(),'tl-test-'));const file=path.join(dir,'bad.zip');const {execFileSync}=require('child_process');const py=`import zipfile,sys\nwith zipfile.ZipFile(sys.argv[1],'w') as z:z.writestr('../escape.txt','bad')`;let python='python';try{execFileSync(python,['-c',py,file])}catch{python='D:\\Program Files\\LibreOffice\\program\\python.exe';execFileSync(python,['-c',py,file])}await assert.rejects(()=>listZip(file),/(路径穿越|invalid relative path)/);await fsp.rm(dir,{recursive:true,force:true});});
test('sha256 is deterministic',()=>assert.equal(sha(Buffer.from('abc')),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'));
test('detection dimensions can be disabled',()=>{const file={zipPath:'a.docx',attributes:{lastEditor:'rare-user',textFingerprint:'0011223344556677'}};const f=correlate([{zipName:'a.zip',supplier:'甲',files:[{...file,sha256:'a'}]},{zipName:'b.zip',supplier:'乙',files:[{...file,sha256:'b'}]}],{metadata:false,simhash:false});assert.equal(f.length,0);});
test('individual file analysis returns grouped properties',async()=>{const dir=await fsp.mkdtemp(path.join(os.tmpdir(),'tl-file-')),file=path.join(dir,'sample.txt');await fsp.writeFile(file,'这是单文件检查示例文本');const p=await analyzeFiles([file]);assert.equal(p.mode,'files');assert.ok(p.submissions[0].files[0].propertyGroups.some(g=>g.id==='common'));await fsp.rm(dir,{recursive:true,force:true});});
test('selected Office metadata fields are removed',()=>{const xml='<cp:coreProperties><dc:creator>张三</dc:creator><cp:lastModifiedBy>李四</cp:lastModifiedBy><dc:title>保留</dc:title></cp:coreProperties>';const cleaned=removeXmlFields(xml,['author','lastEditor']);assert.doesNotMatch(cleaned,/张三|李四/);assert.match(cleaned,/保留/);});
