'use strict';
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const crypto=require('crypto');
const yazl=require('yazl');
const {PDFDocument,PDFName,PDFDict,PDFRawStream,PDFRef,decodePDFRawStream}=require('pdf-lib');
const {openZip,readEntry,sha,analyzeBuffer}=require('./analyzer');

const OFFICE_FIELDS={
  author:{tag:'dc:creator',part:'core'},lastEditor:{tag:'cp:lastModifiedBy',part:'core'},
  title:{tag:'dc:title',part:'core'},subject:{tag:'dc:subject',part:'core'},
  keywords:{tag:'cp:keywords',part:'core'},description:{tag:'dc:description',part:'core'},
  created:{tag:'dcterms:created',part:'core',attrs:' xsi:type="dcterms:W3CDTF"'},
  modified:{tag:'dcterms:modified',part:'core',attrs:' xsi:type="dcterms:W3CDTF"'},
  lastPrinted:{tag:'cp:lastPrinted',part:'core'},revision:{tag:'cp:revision',part:'core'},
  company:{tag:'Company',part:'app'},manager:{tag:'Manager',part:'app'},
  application:{tag:'Application',part:'app'},appVersion:{tag:'AppVersion',part:'app'},template:{tag:'Template',part:'app'}
};
const xmlEscape=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');

async function entryBuffer(zipPath,entryPath){const z=await openZip(zipPath);return new Promise((resolve,reject)=>{let found=false;z.on('entry',async e=>{try{if(e.fileName===entryPath){found=true;const b=await readEntry(z,e);z.close();resolve(b);}else z.readEntry();}catch(x){reject(x)}});z.on('end',()=>{z.close();if(!found)reject(new Error('在 ZIP 中找不到该文件'))});z.on('error',reject);z.readEntry();});}

function removeXmlFields(xml,fields){let s=xml;for(const field of fields){const item=OFFICE_FIELDS[field];if(!item)continue;s=s.replace(new RegExp(`<${item.tag}(?:\\s[^>]*)?>[\\s\\S]*?<\\/${item.tag}>`,'gi'),'');}return s;}
function updateXmlFields(xml,updates,part){let s=xml;for(const [field,value] of Object.entries(updates||{})){const item=OFFICE_FIELDS[field];if(!item||item.part!==part)continue;const body=xmlEscape(value),re=new RegExp(`(<${item.tag}(?:\\s[^>]*)?>)[\\s\\S]*?(<\\/${item.tag}>)`,'i');if(re.test(s))s=s.replace(re,`$1${body}$2`);else{s=s.replace(/<\/[^>]+>\s*$/,`<${item.tag}${item.attrs||''}>${body}</${item.tag}>$&`);}}return s;}

async function cleanOffice(input,fields=[],updates={}){const z=await new Promise((resolve,reject)=>require('yauzl').fromBuffer(input,{lazyEntries:true,decodeStrings:true,autoClose:false},(e,x)=>e?reject(e):resolve(x)));const out=new yazl.ZipFile();const chunks=[];out.outputStream.on('data',c=>chunks.push(c));const finished=new Promise((resolve,reject)=>{out.outputStream.on('end',()=>resolve(Buffer.concat(chunks)));out.outputStream.on('error',reject)});await new Promise((resolve,reject)=>{z.on('entry',async e=>{try{if(/\/$/.test(e.fileName)){out.addEmptyDirectory(e.fileName);z.readEntry();return;}let b=await readEntry(z,e);const match=e.fileName.match(/^docProps\/(core|app)\.xml$/i);if(match){let xml=removeXmlFields(b.toString('utf8'),fields);xml=updateXmlFields(xml,updates,match[1].toLowerCase());b=Buffer.from(xml);}if(/^docProps\/custom\.xml$/i.test(e.fileName)&&fields.includes('customProperties'))b=Buffer.from(b.toString('utf8').replace(/<property\b[\s\S]*?<\/property>/gi,''));out.addBuffer(b,e.fileName,{mtime:new Date(e.getLastModDate())});z.readEntry();}catch(x){reject(x)}});z.on('end',()=>{z.close();resolve()});z.on('error',reject);z.readEntry();});out.end();return finished;}

const parseDate=(value,name)=>{const d=new Date(value);if(Number.isNaN(d.valueOf()))throw new Error(`${name}不是有效日期`);return d;};
const INFO_KEYS={author:'Author',title:'Title',subject:'Subject',keywords:'Keywords',creator:'Creator',producer:'Producer',created:'CreationDate',modified:'ModDate',trapped:'Trapped'};
const XMP_NS={xmp:'http://ns.adobe.com/xap/1.0/',pdf:'http://ns.adobe.com/pdf/1.3/',dc:'http://purl.org/dc/elements/1.1/',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#'};
function infoDict(document){const ref=document.context.trailerInfo.Info;return ref?document.context.lookup(ref,PDFDict):undefined;}
function removeInfoFields(document,fields){const dict=infoDict(document);if(!dict)return;for(const field of fields){const key=INFO_KEYS[field];if(key)dict.delete(PDFName.of(key));}}
function xmpValues(document){const iso=d=>d instanceof Date&&!Number.isNaN(d.valueOf())?d.toISOString():'',dict=infoDict(document),trapped=dict?.get(PDFName.of('Trapped'))?.toString().replace(/^\//,'')||'';return {author:document.getAuthor()||'',title:document.getTitle()||'',subject:document.getSubject()||'',keywords:document.getKeywords()||'',creator:document.getCreator()||'',producer:document.getProducer()||'',created:iso(document.getCreationDate()),modified:iso(document.getModificationDate()),trapped};}
function ensureXmpNamespaces(xml){return xml.replace(/<rdf:Description\b([^>]*)>/i,(all,attrs)=>{let extra='';for(const [prefix,uri] of Object.entries(XMP_NS))if(!new RegExp(`xmlns:${prefix}\\s*=`,'i').test(xml))extra+=` xmlns:${prefix}="${uri}"`;return `<rdf:Description${attrs}${extra}>`;});}
function setSimpleXmp(xml,tag,value){const re=new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`,'gi');if(!value)return xml.replace(re,'');const node=`<${tag}>${xmlEscape(value)}</${tag}>`;if(re.test(xml))return xml.replace(re,node);return xml.replace(/<\/rdf:Description>/i,`${node}</rdf:Description>`);}
function setArrayXmp(xml,tag,container,value){const re=new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`,'gi');if(!value)return xml.replace(re,'');const node=container==='Seq'?`<${tag}><rdf:Seq><rdf:li>${xmlEscape(value)}</rdf:li></rdf:Seq></${tag}>`:`<${tag}><rdf:Alt><rdf:li xml:lang="x-default">${xmlEscape(value)}</rdf:li></rdf:Alt></${tag}>`;if(re.test(xml))return xml.replace(re,node);return xml.replace(/<\/rdf:Description>/i,`${node}</rdf:Description>`);}
function minimalXmp(){return `<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?><x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="${XMP_NS.rdf}"><rdf:Description rdf:about="" xmlns:xmp="${XMP_NS.xmp}" xmlns:pdf="${XMP_NS.pdf}" xmlns:dc="${XMP_NS.dc}"></rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="w"?>`;}
function updateXmpXml(xml,values){let out=ensureXmpNamespaces(xml);out=setSimpleXmp(out,'xmp:CreatorTool',values.creator);out=setSimpleXmp(out,'pdf:Producer',values.producer);out=setSimpleXmp(out,'pdf:Keywords',values.keywords);out=setSimpleXmp(out,'xmp:CreateDate',values.created);out=setSimpleXmp(out,'xmp:ModifyDate',values.modified);out=setSimpleXmp(out,'xmp:MetadataDate',values.modified);out=setSimpleXmp(out,'pdf:Trapped',values.trapped);out=setArrayXmp(out,'dc:creator','Seq',values.author);out=setArrayXmp(out,'dc:title','Alt',values.title);out=setArrayXmp(out,'dc:description','Alt',values.subject);return out;}
function syncXmpMetadata(document){const key=PDFName.of('Metadata'),ref=document.catalog.get(key);let xml='';if(ref){try{const stream=document.context.lookup(ref);if(!(stream instanceof PDFRawStream))throw new Error('Metadata 不是可解码流');xml=Buffer.from(decodePDFRawStream(stream).decode()).toString('utf8');if(!/<rdf:RDF\b/i.test(xml)||!/<rdf:Description\b/i.test(xml))throw new Error('XMP XML 结构无效');}catch{document.catalog.delete(key);return 'removed-invalid';}}else xml=minimalXmp();const updated=updateXmpXml(xml,xmpValues(document)),stream=document.context.flateStream(Buffer.from(updated,'utf8'),{Type:PDFName.of('Metadata'),Subtype:PDFName.of('XML')}),newRef=document.context.register(stream);document.catalog.set(key,newRef);if(ref instanceof PDFRef)document.context.delete(ref);return ref?'updated':'created';}
function patchXmpXml(xml,fields=[],updates={}){let out=ensureXmpNamespaces(xml),value=field=>fields.includes(field)?'':Object.prototype.hasOwnProperty.call(updates,field)?String(updates[field]):undefined;const simple={creator:'xmp:CreatorTool',producer:'pdf:Producer',keywords:'pdf:Keywords',created:'xmp:CreateDate',modified:'xmp:ModifyDate',metadataDate:'xmp:MetadataDate',trapped:'pdf:Trapped'};for(const [field,tag] of Object.entries(simple)){const v=value(field);if(v!==undefined)out=setSimpleXmp(out,tag,v);}const arrays={author:['dc:creator','Seq'],title:['dc:title','Alt'],subject:['dc:description','Alt']};for(const [field,[tag,type]] of Object.entries(arrays)){const v=value(field);if(v!==undefined)out=setArrayXmp(out,tag,type,v);}return out;}
function editXmpMetadata(document,fields=[],updates={}){if(!fields.length&&!Object.keys(updates).length)return 'unchanged';const key=PDFName.of('Metadata'),ref=document.catalog.get(key);let xml=minimalXmp();if(ref){try{const stream=document.context.lookup(ref);if(!(stream instanceof PDFRawStream))throw new Error('Metadata 不是可解码流');const decoded=Buffer.from(decodePDFRawStream(stream).decode()).toString('utf8');if(!/<rdf:RDF\b/i.test(decoded)||!/<rdf:Description\b/i.test(decoded))throw new Error('XMP XML 结构无效');xml=decoded;}catch{xml=minimalXmp();}}const updated=patchXmpXml(xml,fields,updates),stream=document.context.flateStream(Buffer.from(updated,'utf8'),{Type:PDFName.of('Metadata'),Subtype:PDFName.of('XML')}),newRef=document.context.register(stream);document.catalog.set(key,newRef);if(ref instanceof PDFRef)document.context.delete(ref);return ref?'updated':'created';}
async function cleanPdf(input,fields=[],updates={},xmpFields=[],xmpUpdates={},syncMetadata=true){const d=await PDFDocument.load(input,{ignoreEncryption:false,updateMetadata:false});if(d.getForm&&fields.includes('formValues')){const form=d.getForm();for(const field of form.getFields())try{field.clear();}catch{}}
  removeInfoFields(d,fields);
  const set={author:v=>d.setAuthor(v),title:v=>d.setTitle(v),subject:v=>d.setSubject(v),keywords:v=>d.setKeywords(v.split(/[,，;；]/).map(x=>x.trim()).filter(Boolean)),creator:v=>d.setCreator(v),producer:v=>d.setProducer(v),created:v=>d.setCreationDate(parseDate(v,'创建时间')),modified:v=>d.setModificationDate(parseDate(v,'修改时间')),trapped:v=>{const dict=infoDict(d);if(dict)dict.set(PDFName.of('Trapped'),PDFName.of(String(v).replace(/^\//,'')))}};for(const [field,value] of Object.entries(updates||{}))set[field]?.(String(value));if(syncMetadata)syncXmpMetadata(d);else editXmpMetadata(d,xmpFields,xmpUpdates);return Buffer.from(await d.save({useObjectStreams:false}));}

async function writeOutput(destination,output,overwrite){if(!overwrite){await fsp.writeFile(destination,output,{flag:'wx'});return;}const dir=path.dirname(destination),id=crypto.randomUUID(),temp=path.join(dir,`.${path.basename(destination)}.${id}.tmp`),backup=path.join(dir,`.${path.basename(destination)}.${id}.bak`);await fsp.writeFile(temp,output,{flag:'wx'});try{await fsp.rename(destination,backup);try{await fsp.rename(temp,destination);await fsp.rm(backup,{force:true});}catch(error){await fsp.rename(backup,destination);throw error;}}finally{await fsp.rm(temp,{force:true});}}
async function cleanFile({sourcePath,zipPath,entryPath,kind,fields=[],updates={},xmpFields=[],xmpUpdates={},syncMetadata=true,destination,overwrite=false}){if(!fields.length&&!Object.keys(updates).length&&!xmpFields.length&&!Object.keys(xmpUpdates).length)throw new Error('没有需要保存的属性更改');const input=sourcePath?await fsp.readFile(sourcePath):await entryBuffer(zipPath,entryPath);const before=sha(input);let output;if(['word','excel','powerpoint'].includes(kind))output=await cleanOffice(input,fields,updates);else if(kind==='pdf')output=await cleanPdf(input,fields,updates,xmpFields,xmpUpdates,syncMetadata);else throw new Error('当前仅支持编辑 DOCX/XLSX/PPTX 和未加密 PDF 的元数据');await writeOutput(destination,output,overwrite);const verifiedFile=await analyzeBuffer(output,path.basename(destination),{sourcePath:destination});return {destination,beforeSha256:before,afterSha256:sha(output),fields,updates,xmpFields,xmpUpdates,syncMetadata,verifiedFile,createdAt:new Date().toISOString(),originalUntouched:!overwrite};}
module.exports={cleanFile,cleanOffice,cleanPdf,removeXmlFields,updateXmlFields,updateXmpXml,patchXmpXml,syncXmpMetadata,editXmpMetadata};
