'use strict';
const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');const path=require('path');const os=require('os');const fs=require('fs').promises;const {analyzeProject,analyzeFiles}=require('./analyzer');const {saveProject,exportReport,exportHtml}=require('./reports');const {cleanFile}=require('./cleaner');
let win,project;function create(){win=new BrowserWindow({width:1180,height:780,minWidth:900,minHeight:620,backgroundColor:'#f7f8fa',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.removeMenu();win.loadFile(path.join(__dirname,'ui','index.html'));}
app.whenReady().then(create);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)create()});
ipcMain.handle('pick-zips',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections'],filters:[{name:'ZIP 文件',extensions:['zip']}]});return r.canceled?[]:r.filePaths});
ipcMain.handle('pick-files',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections'],filters:[{name:'支持的文档',extensions:['docx','docm','xlsx','xlsm','pptx','pptm','pdf','jpg','jpeg','png','tiff','bmp','webp','txt','csv','xml','json','html']},{name:'所有文件',extensions:['*']}]});return r.canceled?[]:r.filePaths});
ipcMain.handle('analyze',async(_e,files,options={})=>{project=options.mode==='files'?await analyzeFiles(files,{progress:x=>win.webContents.send('progress',x)}):await analyzeProject(files,{detectionOptions:options.detectionOptions,progress:x=>win.webContents.send('progress',x)});return project});
ipcMain.handle('save-review',async(_e,id,state)=>{const f=project?.findings.find(x=>x.id===id);if(f)f.review=state;return !!f});
ipcMain.handle('save-project',async()=>{if(!project)return;const r=await dialog.showSaveDialog(win,{defaultPath:`${project.name}.tenderlens.json`});if(!r.canceled)return saveProject(project,r.filePath)});
ipcMain.handle('open-project',async()=>{const r=await dialog.showOpenDialog(win,{filters:[{name:'投标慧眼项目',extensions:['json']}],properties:['openFile']});if(r.canceled)return null;project=JSON.parse(await fs.readFile(r.filePaths[0],'utf8'));return project});
async function chromiumPdf(p,file){const tmp=path.join(os.tmpdir(),`tenderlens-${Date.now()}.html`);await exportHtml(p,tmp);const w=new BrowserWindow({show:false,webPreferences:{sandbox:true}});try{await w.loadFile(tmp);const data=await w.webContents.printToPDF({printBackground:true,pageSize:'A4',margins:{top:0.5,bottom:0.5,left:0.45,right:0.45}});await fs.writeFile(file,data);}finally{w.destroy();await fs.rm(tmp,{force:true});}}
ipcMain.handle('export',async(_e,type)=>{if(!project)return;const r=await dialog.showSaveDialog(win,{defaultPath:`${project.name}.${type}`});if(!r.canceled){if(type==='pdf')await chromiumPdf(project,r.filePath);else await exportReport(project,type,r.filePath);return r.filePath;}});
ipcMain.handle('clean-file',async(_e,request)=>{const ext=path.extname(request.entryPath||request.sourcePath),base=path.basename(request.entryPath||request.sourcePath,ext);const r=await dialog.showSaveDialog(win,{defaultPath:`${base}-已清理${ext}`});if(r.canceled)return null;return cleanFile({...request,destination:r.filePath});});
ipcMain.handle('show-file',async(_e,p)=>shell.showItemInFolder(p));
