'use strict';
const fs=require('fs').promises; const path=require('path'); const ExcelJS=require('exceljs'); const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function saveProject(p,file){await fs.writeFile(file,JSON.stringify(p,null,2));return file;}
async function exportExcel(p,file){const w=new ExcelJS.Workbook();w.creator='投标慧眼';const s=w.addWorksheet('风险证据');s.columns=[['风险等级','level'],['供应商','suppliers'],['类型','type'],['相关文件','files'],['原始值','value'],['判定依据','reason'],['人工复核','review']].map(([header,key])=>({header,key,width:key==='reason'?45:24}));for(const f of p.findings)s.addRow({...f,suppliers:f.suppliers.join(' ↔ '),files:f.files.join('\n')});s.getRow(1).font={bold:true};s.autoFilter={from:'A1',to:'G1'};s.views=[{state:'frozen',ySplit:1}];const x=w.addWorksheet('文件清单');x.columns=[['供应商','supplier'],['ZIP内路径','zipPath'],['类型','kind'],['字节','size'],['SHA-256','sha256'],['作者','author'],['最后保存作者','lastEditor'],['创建时间','created'],['编辑时间','modified'],['应用程序','application'],['版本号','appVersion'],['PDF版本','pdfVersion'],['文档ID','documentIds'],['SimHash','simhash'],['解析错误','parseError']].map(([header,key])=>({header,key,width:['zipPath','sha256','documentIds'].includes(key)?45:18}));for(const z of p.submissions)for(const f of z.files)x.addRow({...f,author:f.attributes?.author,lastEditor:f.attributes?.lastEditor,created:f.attributes?.created,modified:f.attributes?.modified,application:f.attributes?.application,appVersion:f.attributes?.appVersion,pdfVersion:f.attributes?.pdfVersion,documentIds:(f.attributes?.documentIds||[]).join('\n'),simhash:f.attributes?.textFingerprint});const a=w.addWorksheet('全部属性');a.columns=[['供应商','supplier'],['文件','file'],['属性分类','group'],['属性名称','name'],['属性值','value']].map(([header,key])=>({header,key,width:key==='value'?70:24}));for(const z of p.submissions)for(const f of z.files)for(const g of f.propertyGroups||[])for(const [name,value] of Object.entries(g.items))a.addRow({supplier:z.supplier,file:f.zipPath,group:g.title,name,value:typeof value==='object'?JSON.stringify(value):String(value)});await w.xlsx.writeFile(file);return file;}
async function exportHtml(p,file){const rows=p.findings.map(f=>`<tr><td>${esc(f.level)}</td><td>${esc(f.suppliers.join(' ↔ '))}</td><td>${esc(f.type)}</td><td>${esc(f.reason)}</td><td>${esc(f.review)}</td></tr>`).join('');const files=p.submissions.flatMap(z=>z.files.map(f=>`<section><h3>${esc(z.supplier)} / ${esc(f.zipPath)}</h3>${(f.propertyGroups||[]).map(g=>`<h4>${esc(g.title)}</h4><table>${Object.entries(g.items).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(typeof v==='object'?JSON.stringify(v):v)}</td></tr>`).join('')}</table>`).join('')}</section>`)).join('');const html=`<!doctype html><html lang=zh-CN><head><meta charset=utf-8><title>${esc(p.name)}</title><style>body{font:14px "Microsoft YaHei","PingFang SC",system-ui,sans-serif;margin:36px;color:#172033}table{border-collapse:collapse;width:100%;margin-bottom:16px;page-break-inside:auto}tr{page-break-inside:avoid}td,th{border:1px solid #ccd3df;padding:7px;text-align:left;word-break:break-all}th{background:#f3f5f8}.note{padding:14px;background:#fff7df;border-left:4px solid #d39200}section{page-break-inside:avoid}h2{margin-top:32px}</style></head><body><h1>${esc(p.name)}</h1><p>检测时间：${esc(p.createdAt)}　来源：${p.submissions.length}　文件：${p.submissions.reduce((n,s)=>n+s.fileCount,0)}　风险：${p.findings.length}</p><p class=note>${esc(p.disclaimer)}</p><h2>风险明细</h2><table><thead><tr><th>等级</th><th>供应商</th><th>类型</th><th>原因</th><th>复核</th></tr></thead><tbody>${rows}</tbody></table><h2>全部文件属性</h2>${files}</body></html>`;await fs.writeFile(file,html);return file;}
async function exportPdf(p,file){const d=await PDFDocument.create(),font=await d.embedFont(StandardFonts.Helvetica);let page=d.addPage([595,842]),y=800;const line=(t,size=10,color=rgb(.1,.13,.2))=>{if(y<50){page=d.addPage([595,842]);y=800;}page.drawText(String(t).replace(/[^\x20-\x7E]/g,'?').slice(0,105),{x:42,y,size,font,color});y-=size+7;};line('TenderLens Risk Report',20);line(p.name);line(`Created: ${p.createdAt}  Suppliers: ${p.submissions.length}  Findings: ${p.findings.length}`);line('This report flags correlations for human review; it is not a bid-rigging or legal conclusion.',9,rgb(.65,.35,0));y-=8;for(const f of p.findings){line(`[${f.level}] ${f.type} | ${f.suppliers.join(' <-> ')}`,11);line(f.reason);line(`Files: ${f.files.join(' | ')}`,8);y-=5;}await fs.writeFile(file,await d.save());return file;}
async function exportReport(p,type,file){if(type==='xlsx')return exportExcel(p,file);if(type==='html')return exportHtml(p,file);if(type==='pdf')return exportPdf(p,file);return saveProject(p,file);}
module.exports={saveProject,exportReport,exportExcel,exportHtml,exportPdf};
