'use strict';

const fs=require('fs').promises;
const ExcelJS=require('exceljs');
const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const textValue=value=>typeof value==='object'?JSON.stringify(value):String(value??'');
async function saveProject(project,file){await fs.writeFile(file,JSON.stringify(project,null,2));return file;}
function styleSheet(sheet){sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF2458B5'}};sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:sheet.columnCount}};}
function addSheet(workbook,name,columns){const sheet=workbook.addWorksheet(name);sheet.columns=columns.map(([header,key,width=20])=>({header,key,width}));return sheet;}

async function exportExcel(project,file){
  const workbook=new ExcelJS.Workbook();workbook.creator='TenderGuard';workbook.created=new Date();const audit=project.audit||{};
  const summary=addSheet(workbook,'审查摘要',[['指标','metric',26],['结果','value',28]]);for(const row of [['项目',project.name],['创建时间',project.createdAt],['供应商数量',project.submissions.length],['文件数量',audit.summary?.fileCount??project.submissions.reduce((sum,item)=>sum+item.files.length,0)],['完全相同文件组',audit.summary?.exactFileGroups??0],['属性重复组',audit.summary?.attributeMatchGroups??0],['操作记录',project.operationLog?.length??0],['审查说明',project.disclaimer]])summary.addRow({metric:row[0],value:row[1]});styleSheet(summary);
  const suppliers=addSheet(workbook,'供应商汇总',[['供应商','supplier',30],['ZIP 文件','zipName',36],['文件数','fileCount',12],['总字节','totalSize',16],['ZIP SHA-256','zipSha256',66],['清单哈希','manifestHash',66],['解析异常','parseErrors',12]]);for(const item of audit.supplierStats||project.submissions)suppliers.addRow({...item,parseErrors:item.parseErrors??item.files?.filter(file=>file.parseError).length??0});styleSheet(suppliers);
  const files=addSheet(workbook,'文件清单',[['供应商','supplier',28],['ZIP 内路径','zipPath',48],['类型','kind',14],['字节','size',14],['SHA-256','sha256',66],['作者','author',22],['最后保存者','lastEditor',22],['标题','title',30],['主题','subject',25],['关键词','keywords',25],['创建程序','creator',24],['制作工具','producer',24],['PDF版本','pdfVersion',14],['图片尺寸','dimensions',16],['图片软件','software',20],['解析错误','parseError',35]]);for(const submission of project.submissions)for(const item of submission.files)files.addRow({supplier:submission.supplier,...item,...item.attributes});styleSheet(files);
  const exact=addSheet(workbook,'完全相同文件',[['分组ID','groupId',18],['供应商','supplier',28],['文件','file',48],['字节','size',14],['SHA-256','sha256',66]]);for(const group of audit.exactFiles||[])for(const item of group.files)exact.addRow({groupId:group.id,supplier:item.supplier,file:item.path,size:item.size,sha256:group.sha256});styleSheet(exact);
  const attributes=addSheet(workbook,'属性重复审查',[['分组ID','groupId',18],['文件类型','kind',14],['属性','label',18],['属性值','value',36],['风险等级','riskLevel',12],['权重','weight',10],['供应商','supplier',28],['文件完整路径','file',58]]);for(const group of audit.attributeMatches||[])for(const item of group.files)attributes.addRow({groupId:group.id,kind:group.kind,label:group.label,value:group.value,riskLevel:group.riskLevel||'低风险',weight:group.weight,supplier:item.supplier,file:item.path});styleSheet(attributes);
  const operations=addSheet(workbook,'操作记录',[['时间','at',24],['供应商','supplier',28],['文件','file',48],['操作','action',12],['修改字段','changed',34],['删除字段','deleted',34],['输出文件','destination',48],['验证','verified',10],['修改前 SHA-256','beforeSha256',66],['修改后 SHA-256','afterSha256',66]]);for(const operation of project.operationLog||[])operations.addRow({...operation,action:operation.action==='save'?'保存':'另存为',changed:(operation.changedFields||[]).join('、'),deleted:(operation.deletedFields||[]).join('、')});styleSheet(operations);
  const properties=addSheet(workbook,'全部属性',[['供应商','supplier',28],['文件','file',48],['属性分类','group',22],['属性名称','name',24],['属性值','value',70]]);for(const submission of project.submissions)for(const item of submission.files)for(const group of item.propertyGroups||[])for(const [name,value] of Object.entries(group.items))properties.addRow({supplier:submission.supplier,file:item.zipPath,group:group.title,name,value:textValue(value)});styleSheet(properties);
  await workbook.xlsx.writeFile(file);return file;
}

function table(headers,rows){return `<table><thead><tr>${headers.map(header=>`<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
async function exportHtml(project,file){
  const audit=project.audit||{},supplierRows=(audit.supplierStats||project.submissions).map(item=>[item.supplier,item.zipName,item.fileCount,item.totalSizeLabel||item.totalSize,item.parseErrors||0]),exactRows=(audit.exactFiles||[]).flatMap(group=>group.files.map(item=>[item.supplier,item.path,group.sizeLabel,group.sha256])),attributeRows=(audit.attributeMatches||[]).flatMap(group=>group.files.map(item=>[item.supplier,item.path,`${group.label}：${group.value}`,group.riskLevel||'低风险'])),operationRows=(project.operationLog||[]).map(item=>[new Date(item.at).toLocaleString('zh-CN'),item.supplier,item.file,item.action==='save'?'保存':'另存为',[...(item.changedFields||[]),...(item.deletedFields||[]).map(field=>`删除 ${field}`)].join('、'),item.destination]);
  const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>${esc(project.name)} - TenderGuard</title><style>body{font:13px "Microsoft YaHei","PingFang SC",sans-serif;margin:34px;color:#172033}header{display:flex;align-items:center;gap:12px;border-bottom:3px solid #2864dc;padding-bottom:14px}header b{font-size:22px}header span{color:#667085}h1{font-size:24px;margin:24px 0 5px}h2{font-size:17px;margin-top:28px;color:#1749b5}p{color:#667085}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:18px 0}.kpis div{border:1px solid #d9e0ea;padding:10px}.kpis span{display:block;font-size:10px;color:#667085}.kpis strong{font-size:20px}table{border-collapse:collapse;width:100%;margin:8px 0 18px}td,th{border:1px solid #d9e0ea;padding:6px;text-align:left;word-break:break-all}th{background:#edf3ff}.note{padding:10px;background:#fff7e8;border-left:3px solid #e1a11c}@media print{body{margin:20px}tr{page-break-inside:avoid}}</style></head><body><header><b>TenderGuard</b><span>供应商投标文件审查操作报告</span></header><h1>${esc(project.name)}</h1><p>${esc(project.createdAt)}</p><div class="kpis"><div><span>供应商</span><strong>${project.submissions.length}</strong></div><div><span>文件</span><strong>${audit.summary?.fileCount||0}</strong></div><div><span>相同文件组</span><strong>${audit.summary?.exactFileGroups||0}</strong></div><div><span>属性重复组</span><strong>${audit.summary?.attributeMatchGroups||0}</strong></div></div><div class="note">${esc(project.disclaimer)}</div><h2>供应商汇总</h2>${table(['供应商','ZIP 文件','文件数','文件大小','解析异常'],supplierRows)}<h2>完全相同文件</h2>${exactRows.length?table(['供应商','文件完整路径','文件大小','SHA-256'],exactRows):'<p>未发现</p>'}<h2>属性重复审查</h2>${attributeRows.length?table(['供应商','文件完整路径','重复属性','风险权重'],attributeRows):'<p>未发现</p>'}<h2>操作记录</h2>${operationRows.length?table(['时间','供应商','文件','操作','字段','输出'],operationRows):'<p>本次尚无属性修改操作。</p>'}</body></html>`;
  await fs.writeFile(file,html);return file;
}

async function exportPdf(project,file){const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);let page=doc.addPage([595,842]),y=800;const line=(value,size=10,color=rgb(.1,.13,.2))=>{if(y<50){page=doc.addPage([595,842]);y=800;}page.drawText(String(value).replace(/[^\x20-\x7E]/g,'?').slice(0,105),{x:42,y,size,font,color});y-=size+7;};line('TenderGuard Supplier Review Report',20);line(project.name);line(`Created: ${project.createdAt}  Suppliers: ${project.submissions.length}  Files: ${project.audit?.summary?.fileCount||0}`);line(`Exact groups: ${project.audit?.summary?.exactFileGroups||0}  Attribute groups: ${project.audit?.summary?.attributeMatchGroups||0}  Operations: ${project.operationLog?.length||0}`,9,rgb(.1,.3,.7));for(const group of project.audit?.exactFiles||[]){line(`Exact file ${group.sha256.slice(0,16)}...`,11);for(const item of group.files)line(`${item.supplier} | ${item.path}`,8);y-=4;}await fs.writeFile(file,await doc.save());return file;}
async function exportReport(project,type,file){if(type==='xlsx')return exportExcel(project,file);if(type==='html')return exportHtml(project,file);if(type==='pdf')return exportPdf(project,file);return saveProject(project,file);}

module.exports={saveProject,exportReport,exportExcel,exportHtml,exportPdf};
